spring:
  profiles: local, test
  datasource:
    init-schema: file:./db/migration/schema.sql
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
